Drop table If Exists hocsinh;
CREATE TABLE IF NOT EXISTS HocSinh (
	ID INT(10) NOT NULL auto_increment,
	MaHS NVARCHAR(20) Not NULL,
	HoTenHS NVARCHAR(80) NOT NULL,
	NgaySinh DATETIME(3) NULL DEFAULT NULL,
	Nam BIT NOT NULL,
	DiaChi NVARCHAR(300) NULL DEFAULT NULL,
	PhuHuynh NVARCHAR(100) NULL DEFAULT NULL,
	DTPhuHuynh NVARCHAR(50) NULL DEFAULT NULL,
	EmailPhuHuynh NVARCHAR(50) NULL DEFAULT NULL,
	FaceBookPhuHuynh NVARCHAR(50) NULL DEFAULT NULL,
	GhiChu NVARCHAR(200) NULL DEFAULT NULL,
	InputUserId int(10) NOT NULL,
	InputDate DATETIME(3) NOT NULL,
	NhomHocVien NVARCHAR(50) NULL DEFAULT NULL,
	TenTiengAnh NVARCHAR(50) NULL DEFAULT NULL,
	NgayLienHe DATETIME(3) NULL DEFAULT NULL,
	PRIMARY KEY (ID,MaHs),
    foreign key(InputUserId) references User(Id)
);