use ecdata;
drop table if exists Hocvien_LopHoc;

CREATE TABLE IF NOT EXISTS Hocvien_LopHoc (
	ID INT(10) NOT NULL,
	SoPhieu NVARCHAR(20) NOT NULL,
	IDHocsinh INT(10) NOT NULL,
	IDLop INT(10) NOT NULL,
	IDChiNhanh INT(10) NOT NULL,
	InputUser NVARCHAR(20) NOT NULL,
	InputDate DATETIME(3) NOT NULL,
	NgayHoc DATETIME(3) NOT NULL,
	NgayDangKy DATETIME(3) NOT NULL,
	TuVan NVARCHAR(50) NULL DEFAULT NULL,
	GhiChu NVARCHAR(300) NULL DEFAULT NULL,
	TrangThai NVARCHAR(50) NULL DEFAULT NULL,
	NgayKethuc DATETIME(3) NOT NULL,
	SoBuoiHoc INT(10) NULL DEFAULT NULL,
	TongHocPhi INT(10) NULL DEFAULT NULL,
	IDGoiHocPhi INT(10) NULL DEFAULT NULL,
	NopPhiTheoThang BIT NULL DEFAULT NULL COMMENT '1: nop 1 thang 1, null: nop du khoa',
	IDTuvan INT(10) NULL DEFAULT NULL,
	PRIMARY KEY (ID,IDHocsinh,IDLop,IDChiNhanh)
);